default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: diary_development

test:
  <<: *default
  database: diary_test

production:
  <<: *default
  database: diary_production
  username: diary
  password: <%= ENV['DIARY_DATABASE_PASSWORD'] %>
